# Generated by Django 5.2.17 on 2026-09-10 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140)),
            ],
            options={
                'verbose_name': 'ciudad',
                'verbose_name_plural': 'ciudades',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('codigo_iso', models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='código ISO')),
                ('nombre', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': 'país',
                'verbose_name_plural': 'países',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=140)),
                ('slug', models.SlugField(max_length=140)),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hijas', to='catalogo.categoria')),
            ],
            options={
                'verbose_name': 'categoría',
                'verbose_name_plural': 'categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='AtributoDefinicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.SlugField(max_length=60)),
                ('etiqueta', models.CharField(max_length=120)),
                ('tipo', models.CharField(choices=[('numero', 'Número'), ('opcion', 'Opción'), ('booleano', 'Booleano'), ('texto', 'Texto')], max_length=10)),
                ('unidad', models.CharField(blank=True, max_length=20)),
                ('opciones', models.JSONField(blank=True, default=list)),
                ('obligatorio', models.BooleanField(default=False)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atributos', to='catalogo.categoria')),
            ],
            options={
                'verbose_name': 'definición de atributo',
                'verbose_name_plural': 'definiciones de atributo',
                'ordering': ['categoria', 'orden', 'clave'],
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('proveedora', 'Proveedora'), ('compradora', 'Compradora')], max_length=12)),
                ('razon_social', models.CharField(max_length=200)),
                ('nombre_comercial', models.CharField(blank=True, max_length=200)),
                ('identificador_tributario', models.CharField(max_length=32)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('direccion_fisica', models.CharField(blank=True, max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('estado_verificacion', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=12)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.ciudad')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.pais')),
            ],
            options={
                'verbose_name': 'empresa',
                'ordering': ['razon_social'],
            },
        ),
        migrations.CreateModel(
            name='ContactoEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('cargo', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=40)),
                ('es_principal', models.BooleanField(default=False)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='catalogo.empresa')),
            ],
            options={
                'verbose_name': 'contacto de empresa',
                'verbose_name_plural': 'contactos de empresa',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=140)),
                ('sku', models.CharField(blank=True, max_length=60)),
                ('descripcion_tecnica', models.TextField(blank=True)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=14)),
                ('moneda', models.CharField(default='CLP', max_length=3)),
                ('cantidad_minima_pedido', models.PositiveIntegerField(default=1)),
                ('unidad_empaque', models.CharField(blank=True, max_length=60)),
                ('plazo_entrega_dias', models.PositiveSmallIntegerField(default=0)),
                ('stock_disponible', models.PositiveIntegerField(default=0)),
                ('atributos', models.JSONField(blank=True, default=dict)),
                ('verificado', models.BooleanField(default=False)),
                ('publicado', models.BooleanField(default=False)),
                ('destacado', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='catalogo.categoria')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='catalogo.empresa')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='EscalaPrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volumen_minimo', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=14)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalas_precio', to='catalogo.producto')),
            ],
            options={
                'verbose_name': 'escala de precio',
                'verbose_name_plural': 'escalas de precio',
                'ordering': ['producto', 'volumen_minimo'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='regiones', to='catalogo.pais')),
            ],
            options={
                'verbose_name': 'región',
                'verbose_name_plural': 'regiones',
                'ordering': ['pais', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='empresa',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.region'),
        ),
        migrations.AddField(
            model_name='ciudad',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ciudades', to='catalogo.region'),
        ),
        migrations.AddConstraint(
            model_name='categoria',
            constraint=models.UniqueConstraint(fields=('padre', 'slug'), name='categoria_slug_unico_por_padre'),
        ),
        migrations.AddConstraint(
            model_name='categoria',
            constraint=models.UniqueConstraint(condition=models.Q(('padre__isnull', True)), fields=('slug',), name='categoria_raiz_slug_unico'),
        ),
        migrations.AddConstraint(
            model_name='atributodefinicion',
            constraint=models.UniqueConstraint(fields=('categoria', 'clave'), name='atributo_clave_unica_por_categoria'),
        ),
        migrations.AddConstraint(
            model_name='contactoempresa',
            constraint=models.UniqueConstraint(fields=('empresa', 'email'), name='contacto_email_unico_por_empresa'),
        ),
        migrations.AddConstraint(
            model_name='contactoempresa',
            constraint=models.UniqueConstraint(condition=models.Q(('es_principal', True)), fields=('empresa',), name='un_contacto_principal_por_empresa'),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.UniqueConstraint(fields=('empresa', 'slug'), name='producto_slug_unico_por_empresa'),
        ),
        migrations.AddConstraint(
            model_name='escalaprecio',
            constraint=models.UniqueConstraint(fields=('producto', 'volumen_minimo'), name='escala_volumen_unico_por_producto'),
        ),
        migrations.AddConstraint(
            model_name='region',
            constraint=models.UniqueConstraint(fields=('pais', 'slug'), name='region_slug_unico_por_pais'),
        ),
        migrations.AddConstraint(
            model_name='ciudad',
            constraint=models.UniqueConstraint(fields=('region', 'slug'), name='ciudad_slug_unico_por_region'),
        ),
    ]
