# Generated by Django 5.2.17 on 2026-09-10 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='productos/%Y/%m/')),
                ('alt', models.CharField(blank=True, help_text='Para lectores de pantalla y cuando la imagen no carga.', max_length=160, verbose_name='texto alternativo')),
                ('es_principal', models.BooleanField(default=False)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='catalogo.producto')),
            ],
            options={
                'verbose_name': 'imagen de producto',
                'verbose_name_plural': 'imágenes de producto',
                'ordering': ['producto', '-es_principal', 'orden'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('es_principal', True)), fields=('producto',), name='una_imagen_principal_por_producto')],
            },
        ),
    ]
