# Generated by Django 5.2.17 on 2026-09-11 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_imagenproducto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requerimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_contacto', models.CharField(max_length=120)),
                ('email_contacto', models.EmailField(max_length=254)),
                ('telefono_contacto', models.CharField(blank=True, max_length=40)),
                ('empresa_compradora', models.CharField(blank=True, max_length=200)),
                ('volumen_requerido', models.CharField(blank=True, max_length=120)),
                ('plazo_esperado', models.CharField(blank=True, max_length=120)),
                ('observaciones', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('nuevo', 'Nuevo'), ('en_revision', 'En revisión'), ('respondido', 'Respondido'), ('cerrado', 'Cerrado')], default='nuevo', max_length=15)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requerimientos', to='catalogo.producto')),
            ],
            options={
                'verbose_name': 'requerimiento',
                'ordering': ['-creado'],
            },
        ),
    ]
