# Generated by Django 5.2.17 on 2026-09-11 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_requerimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atributodefinicion',
            name='categoria',
            field=models.ForeignKey(help_text='Categoría donde se define este atributo. Sus subcategorías también lo heredan.', on_delete=django.db.models.deletion.CASCADE, related_name='atributos', to='catalogo.categoria'),
        ),
        migrations.AlterField(
            model_name='atributodefinicion',
            name='clave',
            field=models.SlugField(help_text="Identificador interno sin espacios; es la clave que se usa en el campo 'Atributos' de cada producto.", max_length=60),
        ),
        migrations.AlterField(
            model_name='atributodefinicion',
            name='etiqueta',
            field=models.CharField(help_text='Nombre visible del atributo en la ficha del producto.', max_length=120),
        ),
        migrations.AlterField(
            model_name='atributodefinicion',
            name='obligatorio',
            field=models.BooleanField(default=False, help_text='Si está marcado, todo producto de esta categoría debe incluir este atributo.'),
        ),
        migrations.AlterField(
            model_name='atributodefinicion',
            name='opciones',
            field=models.JSONField(blank=True, default=list, help_text='Solo para tipo Opción: lista de valores válidos en JSON. Ejemplo: ["1 Gbps", "10 Gbps"].'),
        ),
        migrations.AlterField(
            model_name='atributodefinicion',
            name='orden',
            field=models.PositiveSmallIntegerField(default=0, help_text='Controla el orden en que aparece respecto a los demás atributos de la categoría.'),
        ),
        migrations.AlterField(
            model_name='atributodefinicion',
            name='tipo',
            field=models.CharField(choices=[('numero', 'Número'), ('opcion', 'Opción'), ('booleano', 'Booleano'), ('texto', 'Texto')], help_text='Tipo de dato esperado: número, una opción de una lista, sí/no, o texto libre.', max_length=10),
        ),
        migrations.AlterField(
            model_name='atributodefinicion',
            name='unidad',
            field=models.CharField(blank=True, help_text="Unidad a mostrar junto al valor, por ejemplo 'Gbps' o '°C' (opcional).", max_length=20),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(help_text='Nombre visible de la categoría en el catálogo.', max_length=140),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='padre',
            field=models.ForeignKey(blank=True, help_text='Categoría superior, si esta es una subcategoría. Dejalo vacío si es un rubro principal.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hijas', to='catalogo.categoria'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='slug',
            field=models.SlugField(help_text='Parte de la URL para filtrar por esta categoría. Minúsculas y guiones, sin espacios.', max_length=140),
        ),
        migrations.AlterField(
            model_name='contactoempresa',
            name='cargo',
            field=models.CharField(blank=True, help_text='Cargo dentro de la empresa (opcional).', max_length=120),
        ),
        migrations.AlterField(
            model_name='contactoempresa',
            name='email',
            field=models.EmailField(help_text='Correo de contacto. No puede repetirse dentro de la misma empresa.', max_length=254),
        ),
        migrations.AlterField(
            model_name='contactoempresa',
            name='empresa',
            field=models.ForeignKey(help_text='Empresa a la que pertenece este contacto.', on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='catalogo.empresa'),
        ),
        migrations.AlterField(
            model_name='contactoempresa',
            name='es_principal',
            field=models.BooleanField(default=False, help_text='Solo puede haber un contacto principal por empresa; es el que se muestra en el catálogo público.'),
        ),
        migrations.AlterField(
            model_name='contactoempresa',
            name='nombre',
            field=models.CharField(help_text='Nombre de la persona de contacto.', max_length=120),
        ),
        migrations.AlterField(
            model_name='contactoempresa',
            name='telefono',
            field=models.CharField(blank=True, help_text='Teléfono de contacto, con código de país si es posible.', max_length=40),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='ciudad',
            field=models.ForeignKey(help_text='Ciudad donde opera la empresa; tiene que pertenecer a la región elegida.', on_delete=django.db.models.deletion.PROTECT, to='catalogo.ciudad'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Texto breve sobre la empresa para su ficha pública (opcional).'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='direccion_fisica',
            field=models.CharField(blank=True, help_text='Dirección física. Es opcional y no se muestra en el catálogo público.', max_length=255),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='estado_verificacion',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', help_text='Pasala a Aprobada recién cuando confirmaste sus datos. Mientras esté Pendiente no se muestra como verificada.', max_length=12),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='identificador_tributario',
            field=models.CharField(help_text='RUT (Chile) o NIT (Bolivia) de la empresa, sin puntos ni guiones.', max_length=32),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nombre_comercial',
            field=models.CharField(blank=True, help_text='Nombre con el que se muestra en el catálogo público. Si lo dejás vacío, se usa la razón social.', max_length=200),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='pais',
            field=models.ForeignKey(help_text='País donde está constituida la empresa.', on_delete=django.db.models.deletion.PROTECT, to='catalogo.pais'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='razon_social',
            field=models.CharField(help_text='Nombre legal completo, como figura en sus documentos tributarios.', max_length=200),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='region',
            field=models.ForeignKey(help_text='Región (Chile) o departamento (Bolivia) de la empresa.', on_delete=django.db.models.deletion.PROTECT, to='catalogo.region'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='rol',
            field=models.CharField(choices=[('proveedora', 'Proveedora'), ('compradora', 'Compradora')], help_text='Proveedora si vende productos en el catálogo; Compradora si va a enviar requerimientos.', max_length=12),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='slug',
            field=models.SlugField(help_text='Parte de la URL pública de la empresa. Minúsculas y guiones, sin espacios ni tildes.', max_length=140, unique=True),
        ),
        migrations.AlterField(
            model_name='escalaprecio',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, help_text='Precio por unidad a partir de ese volumen, en la moneda del producto.', max_digits=14),
        ),
        migrations.AlterField(
            model_name='escalaprecio',
            name='producto',
            field=models.ForeignKey(help_text='Producto al que aplica esta escala de precio.', on_delete=django.db.models.deletion.CASCADE, related_name='escalas_precio', to='catalogo.producto'),
        ),
        migrations.AlterField(
            model_name='escalaprecio',
            name='volumen_minimo',
            field=models.PositiveIntegerField(help_text='Cantidad mínima desde la que aplica este precio.'),
        ),
        migrations.AlterField(
            model_name='imagenproducto',
            name='es_principal',
            field=models.BooleanField(default=False, help_text='Solo puede haber una imagen principal por producto; es la primera que se ve en el catálogo.'),
        ),
        migrations.AlterField(
            model_name='imagenproducto',
            name='imagen',
            field=models.ImageField(help_text='Archivo de imagen del producto (JPG o PNG).', upload_to='productos/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='imagenproducto',
            name='orden',
            field=models.PositiveSmallIntegerField(default=0, help_text='Controla el orden de esta imagen dentro de la galería.'),
        ),
        migrations.AlterField(
            model_name='imagenproducto',
            name='producto',
            field=models.ForeignKey(help_text='Producto al que pertenece esta imagen.', on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='catalogo.producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='atributos',
            field=models.JSONField(blank=True, default=dict, help_text='Valores técnicos en JSON, con las claves definidas en la categoría. Ejemplo: {"puertos": 24, "poe": true}.'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='cantidad_minima_pedido',
            field=models.PositiveIntegerField(default=1, help_text='Cantidad mínima que un comprador tiene que pedir.'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(help_text='Categoría del producto. De ella hereda los atributos técnicos de más abajo.', on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='catalogo.categoria'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion_tecnica',
            field=models.TextField(blank=True, help_text='Descripción técnica que se muestra en la ficha pública del producto.'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='destacado',
            field=models.BooleanField(default=False, help_text='Los productos destacados aparecen en la portada del sitio.'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='empresa',
            field=models.ForeignKey(help_text='Empresa proveedora dueña de este producto.', on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='catalogo.empresa'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='moneda',
            field=models.CharField(default='CLP', help_text='Código de la moneda del precio, por ejemplo CLP o USD.', max_length=3),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(help_text='Nombre del producto tal como se muestra en el catálogo.', max_length=200),
        ),
        migrations.AlterField(
            model_name='producto',
            name='plazo_entrega_dias',
            field=models.PositiveSmallIntegerField(default=0, help_text='Días hábiles estimados de despacho desde que se confirma el pedido.'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, help_text='Precio por unidad, en la moneda indicada abajo.', max_digits=14),
        ),
        migrations.AlterField(
            model_name='producto',
            name='publicado',
            field=models.BooleanField(default=False, help_text='Solo los productos publicados se muestran en el catálogo público.'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='sku',
            field=models.CharField(blank=True, help_text='Código interno del proveedor (opcional).', max_length=60),
        ),
        migrations.AlterField(
            model_name='producto',
            name='slug',
            field=models.SlugField(help_text='Parte de la URL del producto. Minúsculas y guiones; no se repite dentro de la misma empresa.', max_length=140),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_disponible',
            field=models.PositiveIntegerField(default=0, help_text='Unidades disponibles actualmente.'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='unidad_empaque',
            field=models.CharField(blank=True, help_text="Cómo viene empaquetado, por ejemplo 'caja de 12' (opcional).", max_length=60),
        ),
        migrations.AlterField(
            model_name='producto',
            name='verificado',
            field=models.BooleanField(default=False, help_text='Marcalo cuando el equipo corroboró la información con el proveedor. Se muestra como insignia en el catálogo público.'),
        ),
        migrations.AlterField(
            model_name='requerimiento',
            name='email_contacto',
            field=models.EmailField(help_text='Correo para responderle.', max_length=254),
        ),
        migrations.AlterField(
            model_name='requerimiento',
            name='empresa_compradora',
            field=models.CharField(blank=True, help_text='Empresa que envía el requerimiento, tal como la escribió (texto libre, no vinculado a una Empresa registrada).', max_length=200),
        ),
        migrations.AlterField(
            model_name='requerimiento',
            name='estado',
            field=models.CharField(choices=[('nuevo', 'Nuevo'), ('en_revision', 'En revisión'), ('respondido', 'Respondido'), ('cerrado', 'Cerrado')], default='nuevo', help_text='Estado interno de seguimiento: usalo para saber en qué etapa está este requerimiento.', max_length=15),
        ),
        migrations.AlterField(
            model_name='requerimiento',
            name='nombre_contacto',
            field=models.CharField(help_text='Nombre de la persona que envió el requerimiento.', max_length=120),
        ),
        migrations.AlterField(
            model_name='requerimiento',
            name='observaciones',
            field=models.TextField(blank=True, help_text='Cualquier detalle adicional que haya dejado.'),
        ),
        migrations.AlterField(
            model_name='requerimiento',
            name='plazo_esperado',
            field=models.CharField(blank=True, help_text='Plazo en que espera recibirlo, en sus propias palabras.', max_length=120),
        ),
        migrations.AlterField(
            model_name='requerimiento',
            name='producto',
            field=models.ForeignKey(help_text='Producto sobre el que trata este requerimiento.', on_delete=django.db.models.deletion.PROTECT, related_name='requerimientos', to='catalogo.producto'),
        ),
        migrations.AlterField(
            model_name='requerimiento',
            name='telefono_contacto',
            field=models.CharField(blank=True, help_text='Teléfono de contacto (opcional).', max_length=40),
        ),
        migrations.AlterField(
            model_name='requerimiento',
            name='volumen_requerido',
            field=models.CharField(blank=True, help_text='Volumen que pidió, en sus propias palabras.', max_length=120),
        ),
    ]
