# Generated by Django 5.2.17 on 2026-09-16 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_alter_atributodefinicion_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='calificado',
            field=models.BooleanField(default=False, help_text='Solo lo marca MERCANTE365 desde este panel, nunca el proveedor: revisá el checklist completo antes de activarlo.', verbose_name='Proveedor calificado'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='chk_contacto_revisado',
            field=models.BooleanField(default=False, verbose_name='Contacto revisado'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='chk_direccion_registrada',
            field=models.BooleanField(default=False, verbose_name='Dirección registrada'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='chk_info_comercial_revisada',
            field=models.BooleanField(default=False, verbose_name='Información comercial revisada'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='chk_info_empresarial',
            field=models.BooleanField(default=False, verbose_name='Información empresarial revisada'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='chk_producto_ficha_tecnica',
            field=models.BooleanField(default=False, verbose_name='Producto: ficha técnica'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='chk_producto_fotos_disponibles',
            field=models.BooleanField(default=False, verbose_name='Producto: fotografías disponibles'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='chk_producto_info_comercial',
            field=models.BooleanField(default=False, verbose_name='Producto: información comercial'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='chk_producto_info_disponible',
            field=models.BooleanField(default=False, verbose_name='Producto: información disponible'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='chk_producto_marca_identificada',
            field=models.BooleanField(default=False, verbose_name='Producto: marca identificada'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='chk_sitio_web_revisado',
            field=models.BooleanField(default=False, verbose_name='Sitio web revisado'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='documentacion_estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('recibida', 'Recibida'), ('revisada', 'Revisada')], default='pendiente', max_length=10),
        ),
    ]
