# Generated by Django 5.2.17 on 2026-09-18 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_empresa_calificado_empresa_chk_contacto_revisado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo de la empresa para su perfil público (opcional).', upload_to='empresas/logos/'),
        ),
    ]
