# Generated by Django 5.2.17 on 2026-09-18 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0006_empresa_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('whatsapp', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('zona', models.CharField(blank=True, help_text='Zona donde opera (ciudad o región).', max_length=120)),
                ('especialidad', models.CharField(blank=True, help_text='Rubro en el que se especializa.', max_length=120)),
                ('comision', models.DecimalField(decimal_places=2, default=0, help_text='Comisión por defecto. Se puede pisar por vinculación individual.', max_digits=5, verbose_name='Comisión (%)')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10)),
                ('codigo_referencia', models.SlugField(blank=True, help_text='Código único para su link de referido (?ref=CÓDIGO). Se genera solo desde el nombre si lo dejás vacío.', max_length=40, unique=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'vendedor',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='empresa',
            name='nivel_comercial',
            field=models.CharField(choices=[('free', 'Free'), ('premium', 'Premium'), ('premium_plus', 'Premium Plus')], default='free', help_text='Toggle de nivel comercial (documento de producto, sección 52). Por ahora solo el toggle: los límites reales de cada nivel (tope de productos, etc.) son un módulo aparte todavía no construido. Un proveedor necesita Premium Plus activo para poder vincularse a un vendedor de la Red Comercial.', max_length=12),
        ),
        migrations.AddField(
            model_name='requerimiento',
            name='origen',
            field=models.CharField(choices=[('organico', 'Orgánico'), ('vendedor', 'Vendedor')], default='organico', help_text='Se completa solo si el visitante llegó con un link de referido (?ref=código, documento de producto, secciones 66-67). No lo pisa el comprador.', max_length=10),
        ),
        migrations.AddField(
            model_name='requerimiento',
            name='vendedor',
            field=models.ForeignKey(blank=True, help_text='Vendedor cuyo código de referencia trajo este requerimiento (si el origen es «Vendedor»).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requerimientos', to='catalogo.vendedor'),
        ),
        migrations.CreateModel(
            name='VendedorProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comision', models.DecimalField(blank=True, decimal_places=2, help_text='Dejalo vacío para usar la comisión por defecto del vendedor.', max_digits=5, null=True, verbose_name='Comisión (%)')),
                ('vinculado_en', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendedores', to='catalogo.producto')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculaciones', to='catalogo.vendedor')),
            ],
            options={
                'verbose_name': 'vinculación de vendedor',
                'verbose_name_plural': 'vinculaciones de vendedor',
                'constraints': [models.UniqueConstraint(fields=('vendedor', 'producto'), name='vinculacion_unica_por_producto')],
            },
        ),
    ]
