# Generated by Django 5.2.17 on 2026-09-18 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0007_vendedor_empresa_nivel_comercial_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresa',
            options={'ordering': ['razon_social'], 'permissions': [('gestionar_proveedores', 'Puede gestionar proveedores'), ('gestionar_compradores', 'Puede gestionar compradores'), ('gestionar_calificacion', 'Puede gestionar la calificación de proveedores')], 'verbose_name': 'empresa'},
        ),
    ]
