# Generated by Django 5.2.17 on 2026-09-18 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0009_grupo_staff_completo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oportunidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('nueva', 'Nueva'), ('contactada', 'Contactada'), ('en_cotizacion', 'En cotización'), ('en_negociacion', 'En negociación'), ('ganada', 'Ganada'), ('perdida', 'Perdida')], default='nueva', max_length=15)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('actualizada', models.DateTimeField(auto_now=True)),
                ('requerimiento', models.OneToOneField(help_text='El lead del que nace esta oportunidad.', on_delete=django.db.models.deletion.CASCADE, related_name='oportunidad', to='catalogo.requerimiento')),
            ],
            options={
                'verbose_name': 'oportunidad',
                'ordering': ['-actualizada'],
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('comprobante_externo', models.CharField(blank=True, help_text='Número de factura, boleta u otra referencia externa (opcional).', max_length=120)),
                ('fecha', models.DateField()),
                ('observaciones', models.TextField(blank=True)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('oportunidad', models.OneToOneField(help_text='Tiene que ser una oportunidad en estado «Ganada».', on_delete=django.db.models.deletion.CASCADE, related_name='venta', to='catalogo.oportunidad')),
            ],
            options={
                'verbose_name': 'venta',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Comision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Porcentaje (%)')),
                ('monto', models.DecimalField(decimal_places=2, help_text='Monto de venta × porcentaje. Se calcula solo.', max_digits=12)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('pagada', 'Pagada')], default='pendiente', max_length=10)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('venta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comision', to='catalogo.venta')),
            ],
            options={
                'verbose_name': 'comisión',
                'verbose_name_plural': 'comisiones',
                'ordering': ['-creada'],
            },
        ),
    ]
