# Generated by Django 5.2.17 on 2026-09-19 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0011_permisos_oportunidades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='nivel_comercial',
            field=models.CharField(choices=[('free', 'Free'), ('pyme', 'PYME'), ('premium', 'Premium'), ('premium_plus', 'Premium Plus')], default='free', help_text='Define cuántos productos activos puede tener esta empresa (Free 3 · PYME 7 · Premium 150 · Premium Plus 300). Si la bajás y tiene más productos publicados que el nuevo límite, los más nuevos se desactivan solos (quedan guardados, no se borran). Premium Plus además habilita vincularse a un vendedor de la Red Comercial.', max_length=12),
        ),
    ]
