# Generated by Django 5.2.17 on 2026-09-19 03:58, editado a mano: el orden
# original (RemoveField antes que AddField, sin RunPython) perdía el valor
# de `verificado` de cada producto y dejaba los `estado_verificacion` de
# Empresa con strings viejos ("pendiente"/"aprobada"/"rechazada") que ya no
# están en las choices nuevas — esto remapea los datos existentes en vez de
# perderlos.

from django.db import migrations, models


def migrar_verificado_de_producto(apps, schema_editor):
    Producto = apps.get_model("catalogo", "Producto")
    Producto.objects.filter(verificado=True).update(estado_verificacion="verificado")


def revertir_verificado_de_producto(apps, schema_editor):
    Producto = apps.get_model("catalogo", "Producto")
    Producto.objects.filter(estado_verificacion="verificado").update(verificado=True)


def migrar_estados_de_empresa(apps, schema_editor):
    Empresa = apps.get_model("catalogo", "Empresa")
    Empresa.objects.filter(estado_verificacion="pendiente").update(estado_verificacion="no_verificada")
    Empresa.objects.filter(estado_verificacion="aprobada").update(estado_verificacion="verificada")
    Empresa.objects.filter(estado_verificacion="rechazada").update(estado_verificacion="suspendida")


def revertir_estados_de_empresa(apps, schema_editor):
    Empresa = apps.get_model("catalogo", "Empresa")
    Empresa.objects.filter(estado_verificacion="no_verificada").update(estado_verificacion="pendiente")
    Empresa.objects.filter(estado_verificacion="verificada").update(estado_verificacion="aprobada")
    Empresa.objects.filter(estado_verificacion="suspendida").update(estado_verificacion="rechazada")
    Empresa.objects.filter(estado_verificacion__in=["en_revision", "observada"]).update(estado_verificacion="pendiente")


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0012_alter_empresa_nivel_comercial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='estado_verificacion',
            field=models.CharField(choices=[('no_verificado', 'No verificado'), ('en_revision', 'En revisión'), ('verificado', 'Verificado'), ('observado', 'Observado'), ('suspendido', 'Suspendido')], default='no_verificado', help_text='Pasalo a Verificado cuando el equipo corroboró la información con el proveedor. La insignia pública solo se muestra si además la empresa tiene plan PYME o superior.', max_length=15),
        ),
        migrations.RunPython(migrar_verificado_de_producto, revertir_verificado_de_producto),
        migrations.RemoveField(
            model_name='producto',
            name='verificado',
        ),
        migrations.AlterField(
            model_name='empresa',
            name='estado_verificacion',
            field=models.CharField(choices=[('no_verificada', 'No verificada'), ('en_revision', 'En revisión'), ('verificada', 'Verificada'), ('observada', 'Observada'), ('suspendida', 'Suspendida')], default='no_verificada', help_text='Pasala a Verificada recién cuando MERCANTE365 completó la revisión — nunca se otorga automáticamente por contratar una membresía. La insignia pública solo se muestra si además el plan es PYME o superior (en Free no aplica).', max_length=15),
        ),
        migrations.RunPython(migrar_estados_de_empresa, revertir_estados_de_empresa),
    ]
