# Generated by Django 5.2.17 on 2026-09-19 04:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0013_remove_producto_verificado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='usuario',
            field=models.OneToOneField(blank=True, help_text='La cuenta con la que esta empresa entra a su panel de autoservicio (solo proveedoras, por ahora). Vacío para empresas cargadas desde el back office.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresa', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='slug',
            field=models.SlugField(blank=True, help_text='Parte de la URL pública de la empresa. Minúsculas y guiones, sin espacios ni tildes. Se genera solo desde la razón social si lo dejás vacío.', max_length=140, unique=True),
        ),
    ]
